# Generated by Django 2.0.4 on 2018-04-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180412_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',)},
        ),
    ]
